php-apache:
 build: ./php-apache/
 ports:
 - "10080:80"
 volumes:
 - /app:/app
 links:
 - mysql
mysql:
 build: ./mysql/
 environment:
 - DB_REMOTE_ROOT_NAME=admin
 - DB_REMOTE_ROOT_PASS=admin
 - DB_REMOTE_ROOT_HOST=%
 - DB_USER=dbuser
 - DB_PASS=dbpass
 - DB_NAME=dbname_for_php

